# Generated by Django 2.1.1 on 2018-09-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassicUserAccounts', '0002_auto_20180923_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(blank=True, help_text='This field store a unique user code. ie dealer code, employee code etc.', max_length=20, null=True),
        ),
    ]
