# Generated by Django 2.2.3 on 2019-07-25 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from ClassicUserAccounts.initial_migrations import populate_address


class Migration(migrations.Migration):

    dependencies = [
        ('ClassicUserAccounts', '0009_auto_20190725_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default=None, max_length=250, null=True)),
                ('city', models.CharField(default=None, max_length=100, null=True)),
                ('state', models.CharField(default=None, max_length=100, null=True)),
                ('zip_code', models.CharField(default=None, max_length=20, null=True)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClassicUserAccounts.Country')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_address', to='ClassicUserAccounts.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_address', to='ClassicUserAccounts.Address'),
        ),

        migrations.RunPython(populate_address)
    ]
