# Generated by Django 2.2.3 on 2019-07-26 07:31

import ClassicUserAccounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassicUserAccounts', '0010_auto_20190725_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[ClassicUserAccounts.models.validate_mobile]),
        ),
    ]
